name: Build Wheels (macOS)

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build_wheels_macos_arm64: # Job 1: ARM64
    name: Build wheels on macOS (arm64)
    runs-on: macos-14 # Use ARM runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get libpostal submodule commit hash
        id: get_submodule_hash
        shell: bash
        run: |
          HASH=$(git submodule status vendor/libpostal | awk '{ sub(/^[+-]?/, ""); print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build arm64 wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: arm64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: "python {project}/scripts/test_wheel.py"

      - name: Upload arm64 wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-arm64
          path: ./wheelhouse/*.whl

  build_wheels_macos_x86_64: # Job 2: x86_64
    name: Build wheels on macOS (x86_64)
    runs-on: macos-13 # Use Intel runner (Verify runner availability)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get libpostal submodule commit hash
        id: get_submodule_hash
        shell: bash
        run: |
          HASH=$(git submodule status vendor/libpostal | awk '{ sub(/^[+-]?/, ""); print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build x86_64 wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: x86_64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: "python {project}/scripts/test_wheel.py"

      - name: Upload x86_64 wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-x86_64
          path: ./wheelhouse/*.whl
