name: Build Wheels (macOS)

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

env: # Define common vars at workflow level
  CIBW_BUILD_COMMON: "cp311-* cp312-*"
  CIBW_SKIP_COMMON: "pp* *-musllinux_* cp37-win*"
  CIBW_TEST_COMMAND_COMMON: "python {project}/scripts/test_wheel.py"
  CIBW_BUILD_VERBOSITY_COMMON: "1"

jobs:
  build_wheels_macos: # Single job using matrix
    name: Build wheels on macOS (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            runner: macos-14 # ARM runner
          - arch: x86_64
            runner: macos-13 # Intel runner (Verify runner availability)
    runs-on: ${{ matrix.runner }} # Use matrix runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get libpostal submodule commit hash
        id: get_submodule_hash
        shell: bash
        run: |
          HASH=$(git submodule status vendor/libpostal | awk '{ sub(/^[+-]?/, ""); print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      - name: Build wheels (${{ matrix.arch }})
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ env.CIBW_BUILD_COMMON }}
          CIBW_SKIP: ${{ env.CIBW_SKIP_COMMON }}
          CIBW_BUILD_VERBOSITY: ${{ env.CIBW_BUILD_VERBOSITY_COMMON }}
          CIBW_TEST_COMMAND: ${{ env.CIBW_TEST_COMMAND_COMMON }}
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: ${{ matrix.arch }}

      - name: Upload wheels (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
